### ISSUE TITLE
Array format for provided/returned data

### ISSUE THREAD

**Issue by jlnav** [campa-consortium/generator_standard#1]
What library/data-type should Generators receive/return data in?

- libEnsemble uses NumPy NDArrays.
- Optimas asks/tells Trials, containing trail_data, containing dicts, lists, NDArrays, or Pandas dataframes
- Xopt uses Pandas dataframes
- rsopt runs libEnsemble to completion on some simulation (?)

(I may have gotten some detail wrong)

No matter what format generators handle data in, I imagine everyone will convert into whatever format they'd prefer for internal work.

- Could a generator superclass contain methods for converting data?
- Similarly to Optimas, could the standard accept/return some higher-level wrapper-object?
- Do we support other popular formats? e.g. Dask, Polars, HDF5 etc.

**Comment by roussel-ryan** [comment]
Some thoughts on this discussion:
- python is a dictionary based language, so to take advantage of this we should return a "dictionary-like" object
- the return type should be as close as possible to fundamental python types as is reasonable
-> we initially considered returning either a list of dicts or a dict that contained lists, however this can create issues when returning one vs many points as users wanted to return a single dict if one point was requested but this is inconsistent typing when returning multiple points (dict vs. list[dict])
-> pandas is a way to unify the output in these cases (which is why we used it in Xopt), although it is fairly high-level, which violates the second bullet above, and might encounter computational inefficiencies (is this important (?), might not be in many cases). However, it is easy to convert to/from a variety of data types/dump to files/visualization. It also can store a variety of different data types in a single object

Also I believe that libEnsemble uses structured arrays correct? I personally am not a huge fan of this object type due to its dtype specification, but I could take another look if we would prefer that approach and it addresses the issues above

**Comment by jlnav** [comment]
The list-of-dicts potential is interesting. Regarding returning one point, was something like `[{"x1": 0.1, "x2": 0.2}]` not preferred by your users?

Yeah, libEnsemble uses numpy structured arrays, and although we believe they're fast/flexible enough, yeah, dealing with dtypes can be challenging. Though, Angel pointed out within the last few months that structured arrays can be made somewhat more flexible if the dtype is set to `object`:

```
>>> import numpy as np
>>> data = np.zeros(10, dtype=object)
>>> data[0:5] = ["h", "e", "l", "l", "o"]
>>> data
array(['h', 'e', 'l', 'l', 'o', 0, 0, 0, 0, 0], dtype=object)
>>> data[6] = 3.14
>>> data[7:10] = 999
>>> data
array(['h', 'e', 'l', 'l', 'o', 0, 3.14, 999, 999, 999], dtype=object)
>>> fields = np.zeros(10, dtype=[("x", object, 2), ("f", object)])
>>> fields
array([([0, 0], 0), ([0, 0], 0), ([0, 0], 0), ([0, 0], 0), ([0, 0], 0),
       ([0, 0], 0), ([0, 0], 0), ([0, 0], 0), ([0, 0], 0), ([0, 0], 0)],
      dtype=[('x', 'O', (2,)), ('f', 'O')])
>>> fields["x"] = [123, "GPU"]
```

Either way, I believe it would be best if the return-type (not necessarily size, of course) is consistent, e.g.:

`def ask() -> List[dict]:` or `def ask() -> NDArray:`

instead of:

`def ask() -> Union[dict, list]`, implying either a dictionary _or_ a list.

---

An aside, I'm wondering if `ask(num_points=0)` should return `None` or an empty array. I'm leaning towards an empty array to keep the return-type as consistent as possible.

**Comment by RemiLehe** [comment]
From our discussion:

We want to support 2 applications of the standardized generator:
- Within frameworks such as `Xopt`, `optimas`, etc: as a way to be able to use any generator from the other packages, without having to write custom wrappers for each generator.
- A user that does not use the default, vanilla `Xopt` or `optimas` workflow (whereby the generator's `ask` and `tell` are called by `Xopt`, `optimas`, etc.) should also be able to directly call the generator's `ask` and `tell`.

Because of the second requirement, it would be good if the data types for `ask` and `tell` is well-known and easy to use. Candidates are:
- Dictionary of lists (where the lists have one element per evaluation). Pro: does not need any external library. Con: does not check that all lists have the same length.
- Numpy structured array. Pro: checks that all lists have the same length. Con: less well-known, not as easy to create as dict of lists
- Pandas dataframe. Pro: checks that all lists have the same length. Con: heavy dependency, not as easy to create as dict of lists

Note that all the above objects support the interface: `X['some_name'] -> Iterable (with one element per evaluation)`

**Comment by AngelFP** [comment]
For completeness, I would still add to the list the option of a custom Class. I believe this to be the most flexible and easy to extend solution in the long run. As @cchall said, this is what other libraries already do, and I can add to that the interfaces of Ax and optuna (https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/009_ask_and_tell.html), which are both widely used.

Some advantages I see in this approach (with some pseudocode examples) :

- it can make the trials self-descriptive (ie, not only store the value name and value of the variables, but also to know which ones are objectives, parameters to vary, etc.)

```python
for obj in trial.objectives:
    print(f"obj = {trial.data[obj]}")
```

- It allows us to add attributes that might not fit well in an array or dataframe.

- It allows us to define methods in the trial.

```python
trial.complete(evaluation_data)
generator.tell(trial)
```

- We could implement more advanced data validation, e. g., by using pydantic. 

Most of this has been quite useful in optimas, where I also went with this approach.

**Comment by shuds13** [comment]
Trying to list pros/cons of numpy array v objects.

numpy structured arrays pros:
 - nice to slice and dice array e.g., H['x'][:50]
 - numpy also tending to be faster
   - and can directly use all the numpy functions on it.

list of objects pros:
 - Can define member functions
 - Easier to nest
  e.g., with list of objects each can have a variable which is its own object with data like upper/lower bounds kept together.
 - Accessing elements has cleaner syntax.
 - More intuitive setup.

Dataframe libraires (Pandas/Polars)
 - Ease of operating on data and analysis tools.
 - Pandas more existing integrations - Polars faster and more memory efficient.
